
image:
  file: .gitpod.Dockerfile

tasks:
  - init: make data-cleanup


vscode:
  extensions:
    - jock.svg
    - ms-python.python
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter
    - ms-azuretools.vscode-docker
